import { FileDNA } from '../types/dna';

/**
 * Metric item for tabular or key-value presentation.
 */
export interface ExplanationMetric {
  readonly label: string;
  readonly value: string;
  readonly badge?: string;
  readonly highlight?: boolean;
}

/**
 * Deterministic recommendation for an applicable next tool.
 */
export interface ExplanationRecommendation {
  readonly toolId: string;
  readonly reason: string;
  readonly priority: 'high' | 'medium' | 'low';
}

/**
 * Structured explanation result generated by Explain Engine.
 * Guaranteed to be pure data (no JSX/UI dependencies).
 */
export interface FileExplanation {
  /** Concise one-line summary of file state */
  readonly summary: string;

  /** What a target tool will do, if a target tool is specified in context */
  readonly targetToolExplanation?: string;

  /** Explicit local-first privacy statement */
  readonly privacyNotice: string;

  /** Structured metrics derived from FileDNA */
  readonly metrics: readonly ExplanationMetric[];

  /** Deterministic tool recommendations based on file attributes */
  readonly recommendations: readonly ExplanationRecommendation[];

  /** Critical warnings (e.g. canvas limits exceeded, corrupt file) */
  readonly warnings: readonly string[];

  /** True if the file can proceed to processing */
  readonly isActionable: boolean;
}

/**
 * Context provided to generateFileExplanation.
 */
export interface ExplainContext {
  /** Target tool ID the file is currently being loaded into, if any */
  readonly targetToolId?: string;

  /** Optional parameters configured on the tool */
  readonly customOptions?: Readonly<Record<string, unknown>>;
}

const TOOL_DESCRIPTIONS: Record<string, string> = {
  'image-compressor': 'Compresses file size while preserving resolution. Runs off-screen canvas encoding in browser memory.',
  'image-resizer': 'Scales dimensions using bicubic interpolation. Preserves or adjusts aspect ratio safely.',
  'image-cropper': 'Interactive crop bounding box to isolate the exact area of interest.',
  'image-converter': 'Converts image formats (JPEG, PNG, WebP) entirely on this device.',
  'image-to-pdf': 'Assembles images into a standardized PDF document with configurable page margins.',
  'pdf-to-image': 'Extracts document pages and renders them as high-resolution image files.',
  'text-counter': 'Calculates detailed typographic, word, character, and line statistics.',
  'text-cleaner': 'Normalizes line breaks, collapses excessive spacing, and trims edge whitespace.',
  'case-converter': 'Transforms text casing into Title Case, UPPERCASE, lowercase, or camelCase.',
  'qr-scanner': 'Reads and decodes QR codes from image data with protocol safety verification.',
  'qr-generator': 'Encodes text or URLs into high-contrast QR code vector/raster images.',
};

/**
 * PHONE TOOLS — Explain Engine
 *
 * Deterministically explains file characteristics and processing impact
 * BEFORE any mutation or tool execution occurs.
 *
 * Invariants:
 * - 100% deterministic rule engine: No AI, no APIs, no network, no random output.
 * - Pure data contract: Returns structured TypeScript records, never JSX.
 * - Privacy-first: Zero data transmission, zero storage, zero Base64.
 * - Zero execution: Explains only; never modifies files or triggers processing.
 */
export function generateFileExplanation(
  dna: FileDNA,
  context?: ExplainContext
): FileExplanation {
  const privacyNotice = 'Processing will happen entirely on this device. Your file is never uploaded.';
  const warnings: string[] = [];
  const metrics: ExplanationMetric[] = [];
  const recommendations: ExplanationRecommendation[] = [];

  const { universal, image, pdf, text, health } = dna;

  // 1. Health & Validity Checks
  if (health.isCorrupt || !health.isValidMime) {
    const errorMsg = health.errorReason || 'The file appears corrupted or uses an unreadable format.';
    warnings.push(errorMsg);

    return {
      summary: 'Unsupported or unreadable file.',
      privacyNotice,
      metrics: [
        { label: 'File Type', value: universal.extension.toUpperCase() || 'Unknown' },
        { label: 'File Size', value: universal.humanSize },
        { label: 'Status', value: 'Unreadable', highlight: true },
      ],
      recommendations: [],
      warnings,
      isActionable: false,
    };
  }

  let summary = `${universal.extension.toUpperCase()} file (${universal.humanSize})`;
  let isActionable = true;

  // 2. Image Specific Explanation
  if (universal.mediaType === 'image' && image) {
    summary = `${universal.extension.toUpperCase()} image (${universal.humanSize}, ${image.width} × ${image.height} px)`;

    metrics.push(
      { label: 'Format', value: universal.extension.toUpperCase() },
      { label: 'File Size', value: universal.humanSize },
      { label: 'Dimensions', value: `${image.width} × ${image.height} px` },
      { label: 'Aspect Ratio', value: image.aspectRatio },
      { label: 'Resolution', value: `${image.megapixels} MP` }
    );

    if (image.isAnimated) {
      metrics.push({ label: 'Animation', value: 'Animated frames detected', badge: 'GIF' });
    }

    // Canvas safety warning
    if (image.exceedsCanvasLimit) {
      warnings.push(
        'Dimensions exceed safe browser limits (8192px / 67MP). Resizing is strongly recommended before processing.'
      );
      recommendations.push({
        toolId: 'image-resizer',
        reason: 'Oversized dimensions may cause browser canvas exhaustion. Resize down to standard resolution.',
        priority: 'high',
      });
    } else if (image.width > 2560 || image.height > 2560) {
      recommendations.push({
        toolId: 'image-resizer',
        reason: 'High resolution image (over 2.5K). Downscaling can optimize web sharing and display.',
        priority: 'medium',
      });
    }

    // Size-based compression recommendation
    if (universal.byteSize > 2 * 1024 * 1024) {
      recommendations.push({
        toolId: 'image-compressor',
        reason: `File is large (${universal.humanSize}). Compression can significantly reduce file weight.`,
        priority: 'high',
      });
    }

    // Format conversion recommendation
    if (universal.extension !== 'webp' && universal.extension !== 'svg') {
      recommendations.push({
        toolId: 'image-converter',
        reason: 'Converting to WebP format often yields 25%–35% smaller file size with equivalent quality.',
        priority: 'low',
      });
    }
  }

  // 3. PDF Specific Explanation
  else if (universal.mediaType === 'pdf' && pdf) {
    if (pdf.isEncrypted) {
      summary = `Encrypted PDF document (${universal.humanSize})`;
      warnings.push('This PDF document is password-protected and must be unlocked before processing.');
      isActionable = false;

      metrics.push(
        { label: 'Format', value: 'PDF' },
        { label: 'File Size', value: universal.humanSize },
        { label: 'Protection', value: 'Password Encrypted', highlight: true }
      );
    } else {
      const pageText = pdf.pageCount === 1 ? '1 page' : `${pdf.pageCount} pages`;
      summary = `PDF document (${universal.humanSize}, ${pageText})`;

      metrics.push(
        { label: 'Format', value: 'PDF' },
        { label: 'File Size', value: universal.humanSize },
        { label: 'Page Count', value: `${pdf.pageCount}` }
      );

      recommendations.push({
        toolId: 'pdf-to-image',
        reason: 'Extract pages as crisp PNG or JPEG image files.',
        priority: 'medium',
      });
    }
  }

  // 4. Text Specific Explanation
  else if (universal.mediaType === 'text' && text) {
    summary = `Text document (${universal.humanSize}, ${text.wordCount.toLocaleString()} words)`;

    metrics.push(
      { label: 'Format', value: universal.extension.toUpperCase() || 'TXT' },
      { label: 'File Size', value: universal.humanSize },
      { label: 'Words', value: text.wordCount.toLocaleString() },
      { label: 'Characters', value: text.charCount.toLocaleString() },
      { label: 'Lines', value: text.lineCount.toLocaleString() },
      { label: 'Whitespace', value: `${Math.round(text.whitespaceRatio * 100)}%` }
    );

    if (text.whitespaceRatio > 0.25) {
      recommendations.push({
        toolId: 'text-cleaner',
        reason: 'High proportion of whitespace characters detected. Clean extra spaces and empty lines.',
        priority: 'medium',
      });
    }

    recommendations.push({
      toolId: 'case-converter',
      reason: 'Change text casing to Sentence case, Title Case, or UPPERCASE.',
      priority: 'low',
    });
  }

  // 5. Binary / Fallback Explanation
  else {
    metrics.push(
      { label: 'Format', value: universal.extension.toUpperCase() || 'Binary' },
      { label: 'File Size', value: universal.humanSize }
    );
  }

  // Target tool contextual explanation
  let targetToolExplanation: string | undefined = undefined;
  if (context?.targetToolId && TOOL_DESCRIPTIONS[context.targetToolId]) {
    targetToolExplanation = TOOL_DESCRIPTIONS[context.targetToolId];
  }

  return {
    summary,
    targetToolExplanation,
    privacyNotice,
    metrics,
    recommendations,
    warnings,
    isActionable,
  };
}
